### ISSUE TITLE
Config module rules uses (loaders): modifying options example not working

### ISSUE THREAD

**Issue by ArkhipovK** [mozilla-neutrino/webpack-chain#78] opened 2018-07-21 13:41 UTC
[This](https://github.com/mozilla-neutrino/webpack-chain#config-module-rules-uses-loaders-modifying-options) example doesn't work.
This part of code
```
chainWebpack: config => {
        config.module
            .rule('vue')
                .use("vue-loader")
                    .tap(options =>  merge(options, { transformAssetUrls:{ 'parallax': 'src',} }))
    }
```
fail with ` ReferenceError: merge is not defined` error. Should i import it from somewhere?

**Comment by edmorley** [comment] 2018-07-23 11:07
Hi! `merge()` is whatever merge function you may want to use - though commonly will be babel-merge. 

Duplicate of #67.

**Closed by edmorley** 2018-07-23 11:07 UTC
